# NOTE: Generated By HttpRunner v4.3.5
# FROM: api_test_cases.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseApiTestCases(HttpRunner):

    config = (
        Config("AI测试用例转换服务测试套件")
        .variables(
            **{
                "test_case_desc": "测试用户登录功能，验证用户名密码正确时返回200状态码",
                "test_script_content": "import unittest import requests\nclass TestLogin(unittest.TestCase):\n    def test_successful_login(self):\n        url = 'http://example.com/login'\n        data = {'username': 'test_user', 'password': 'test_pass'}\n        response = requests.post(url, data=data)\n        self.assertEqual(response.status_code, 200)",
            }
        )
        .base_url("http://localhost:8003")
    )

    teststeps = [
        Step(
            RunRequest("测试健康检查接口")
            .get("/health")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "healthy")
        ),
        Step(
            RunRequest("测试转换单个测试用例接口")
            .post("/api/v1/convert-test-case")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "test_case_description": "$test_case_desc",
                    "template_type": "pytest",
                    "generation_type": "script",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
            .assert_type_match("body.generated_script", "str")
        ),
        Step(
            RunRequest("测试批量转换测试用例接口")
            .post("/api/v1/batch-convert")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "test_cases": ["$test_case_desc", "测试用户注册功能，验证必填字段为空时返回400状态码"],
                    "template_type": "pytest",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
            .assert_type_match("body.results", "list")
            .assert_length_equal("body.results", 2)
        ),
        Step(
            RunRequest("测试执行测试脚本接口")
            .post("/api/v1/execute-test")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"script_content": "$test_script_content"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.success", True)
        ),
        Step(
            RunRequest("测试分析测试结果接口")
            .post("/api/v1/analyze-results")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "test_case": "$test_case_desc",
                    "execution_result": {
                        "success": True,
                        "output": "Test passed!",
                        "error": None,
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.success", True)
            .assert_type_match("body.analysis", "str")
        ),
    ]


if __name__ == "__main__":
    TestCaseApiTestCases().test_start()
