# NOTE: Generated By HttpRunner v4.3.5
# FROM: local_http_test.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseLocalHttpTest(HttpRunner):

    config = Config("本地HTTP服务器测试").base_url("http://localhost:8000")

    teststeps = [
        Step(
            RunRequest("测试根路径访问").get("/").validate().assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("测试index.html访问")
            .get("/index.html")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("测试不存在的路径(验证404)")
            .get("/non_existent_file.html")
            .validate()
            .assert_equal("status_code", 404)
        ),
        Step(
            RunRequest("测试目录列表访问").get("/").validate().assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLocalHttpTest().test_start()
