# NOTE: Generated By HttpRunner v4.3.5
# FROM: public_api_test.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCasePublicApiTest(HttpRunner):

    config = Config("公共API测试套件").base_url("https://httpbin.org")

    teststeps = [
        Step(
            RunRequest("测试GET请求")
            .get("/get")
            .validate()
            .assert_equal("status_code", 200)
            .assert_type_match("body.args", "dict")
            .assert_type_match("body.headers", "dict")
        ),
        Step(
            RunRequest("测试POST请求")
            .post("/post")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "test_user", "password": "test_password"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.json.username", "test_user")
            .assert_equal("body.json.password", "test_password")
        ),
        Step(
            RunRequest("测试状态码404")
            .get("/status/404")
            .validate()
            .assert_equal("status_code", 404)
        ),
        Step(
            RunRequest("测试延迟响应")
            .get("/delay/1")
            .set_timeout(5)
            .validate()
            .assert_equal("status_code", 200)
            .assert_type_match("body.url", "str")
        ),
    ]


if __name__ == "__main__":
    TestCasePublicApiTest().test_start()
