# NOTE: Generated By HttpRunner v4.3.5
# FROM: test_httprunner_demo.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseTestHttprunnerDemo(HttpRunner):

    config = Config("HttpRunner 测试示例").variables(**{"base_url": "https://httpbin.org"})

    teststeps = [
        Step(
            RunRequest("发送 GET 请求测试")
            .get("$base_url/get")
            .with_params(**{"test": "httprunner"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_contains("body.args.test", "httprunner")
        ),
        Step(
            RunRequest("发送 POST 请求测试")
            .post("$base_url/post")
            .with_json({"username": "test_user", "password": "test_password"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.json.username", "test_user")
        ),
    ]


if __name__ == "__main__":
    TestCaseTestHttprunnerDemo().test_start()
